### ISSUE TITLE
tests: Add option to select FIPS202 AArch64 backend

### ISSUE THREAD

**Issue by hanno-becker** [pq-code-package/mlkem-native#1009]
By default, mlkem-native will use compiler-specified feature flags to decide which FIPS202 implementation to use. To overwrite this default behaviour, one currently has to specify the backend file directly, which is rather cumbersome. See e.g. `bench.yml`:
```yaml
        - system: a55
          name: Arm Cortex-A55 (Snapdragon 888) benchmarks
          bench_pmu: PERF
          archflags: "-mcpu=cortex-a55 -march=armv8.2-a"
          cflags: "-flto -static -DMLK_FORCE_AARCH64 -DMLK_CONFIG_FIPS202_BACKEND_FILE=\\\\\\\"fips202/native/aarch64/x1_scalar.h\\\\\\\""
          bench_extra_args: -w exec-on-a55
```

Task: Add command line option `--fips202-backend` to the `tests` script which provides a more convenient way to select the FIPS202 backend on AArch64 systems.
